### PR TITLE
Fix 102063901

### PR DESCRIPTION
**Pull request by pathmapper**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1697

Updated some properties, most of them related to `statoids` (http://www.statoids.com/yde.html).

Also updated with the correct geometry from `de-bkg`.

Validated with `wof-validate-properties` and `wof-validate-geometry`.

To Do:

- [x]  `geom:area`
- [ ]  `geom:area_square_m`
- [x]  `geom:latitude`
- [x]  `geom:longitude`
- [ ]  [update alt geometry ](https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/102/063/901/102063901-alt-quattroshapes.geojson)

https://whosonfirst.org/docs/properties/geom/ states that these properties are derived from Shapely.
Is it a must to use Shapely or is it ok to calculate these properties also e.g. with QGIS?
If Shapely should be used, is there a script somewhere for this task?
What is the unit of `geom:area`?

### CODE REVIEW

**Comment by missinglink** [comment]
I think the ['exportify'](https://github.com/whosonfirst/docker-whosonfirst-exportify) tool can help setting those properties.

**Comment by pathmapper** [comment]
Thanks @missinglink, used the tool in https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/13/commits/9e68f927269a0d45c2dd1803c799cc117e2382e7 

The centroid coordinates ( `geom:latitude` and `geom:longitude`) and `geom:area` were updated.

` geom:area_square_m` still needs an update and I still wonder which unit is used for `geom:area`, since this value is now `0.279932`.

**Comment by pathmapper** [comment]
[Quattroshapes download links are down](https://github.com/foursquare/quattroshapes/issues/10), at least since January 2018, so remove the alt geometry and related properties?

**Comment by pathmapper** [comment]
Hmm, there is another id, which has the correct geometry but also some Oldenburg data:
https://spelunker.whosonfirst.org/id/102063947/

Seems like "Kreisfreie Stadt Osnabrück" and "Landkreis Osnabrück" have some properties swapped with each other and also mixed with some Oldenburg data. The questions is which id should belong to which one:
Landkreis Osnabrück -> 102063901
Kreisfreie Stadt Osnabrück -> 102063947
or vice versa?

**Comment by missinglink** [comment]
Regarding 'area', it's not clear what unit it is..

I can see from the code that python is calling the shapely library but shapely docs don't specify.

- https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L302
- https://shapely.readthedocs.io/en/stable/manual.html#object.area

**Comment by stepps00** [comment]
Thanks for the issue and PR, @pathmapper.

>Is it a must to use Shapely or is it ok to calculate these properties also e.g. with QGIS? If Shapely should be used, is there a script somewhere for this task?

As @missinglink pointed out, the [Exportify tool](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/scripts/wof-exportify) should set the `geom:*` properties for you.

> What is the unit of geom:area?

Shapely uses the Cartesian system, the units you see should be in meters/square meters.

Overall, I agree with the statoids/population/name changes, they all look great. I'm having issues with viewing the geometry diff, though, so I'll need to check the changes out in QGIS. We recently refactored many of the geometries in Germany as part of https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1 and have contiguous coverage at most placetypes... I'll poke around with these changes and follow up with any notes.

Thanks!

**Comment by pathmapper** [comment]
> shapely docs don't specify

Found this post: https://gis.stackexchange.com/a/166682/105333

> Whichever units are represented by the coordinates in your geometries.
> Shapely geometries are Cartesian and make no assumptions about being Lon/Lat or anything else.

Shapely docs: https://shapely.readthedocs.io/en/stable/manual.html#coordinate-systems

So there is no unit in our case. Wonder why the `geom:area` property exists for WOF data ...

**Comment by pathmapper** [comment]
@stepps00 thanks for your feedback.

> Exportify tool should set the geom:* properties for you

There is a property `geom:area_square_m`, which wasn't set by the Exportify tool. Could be also related to the [docker version of the tool](https://github.com/whosonfirst/docker-whosonfirst-exportify#wof-exportify-www) which I used.

> the units you see should be in meters/square meters.

The exportify tool calculated `0.279932` for `geom:area`, so I doubt these are square meters. Also there is a seperate property `geom:area_square_m`. Possible explanation in my https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/13#issuecomment-523057976 above.

Regarding the geometries:

https://spelunker.whosonfirst.org/id/102063947/ and
https://spelunker.whosonfirst.org/id/102063901/ (modified in this PR)
are complementary. We could also leave the geometries for both IDs as they are and fix the properties (which would mean also to swap the label properties `eng_x_preferred_longname` and `deu_x_preferred_longname`).

**Comment by pathmapper** [comment]
The `geom:area_square_m` issue [is related to the docker tool](https://github.com/whosonfirst/docker-whosonfirst-exportify/issues/4#issuecomment-523113131), submitted https://github.com/whosonfirst/docker-whosonfirst-exportify/pull/5 to fix this.

**Comment by pathmapper** [comment]
Fresh PR in https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/17

**Pull request closed without merging**
