### PR TITLE
Update Place Neuegling

### PR DESCRIPTION
**Pull request by stepps00**
Updating `data/137/780/533/3/1377805333.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by stepps00** [comment]
Place shares the name with this railway station: https://en.wikipedia.org/wiki/Neugilching_station

**Review by nvkelso — APPROVED** [review]
Is it possible to also add the Wikidata concordance then? Looks to be:

- https://www.wikidata.org/wiki/Q552131

**Comment by stepps00** [comment]
>Is it possible to also add the Wikidata concordance then? Looks to be:

> https://www.wikidata.org/wiki/Q552131

This is for the municipality (locality) of Gilching, which is north of this record.. this record is for a neighbourhood for Neugilching, which I can't find a Wikidata concordance for, unfortunately..

**Comment by stepps00** [comment]
Will merge as-is, but can come back to this record if we'd like to adjust further.

**Pull request merged**
